#!/usr/bin/env bash
# Generates version.h next to this script.
#
# FIRMWARE_VERSION is "<MAJOR>.<commits>" where <commits> = `git rev-list --count HEAD`.
# Appends "-dev" if the working tree has uncommitted changes.
# Examples: "3.147", "3.147-dev".
#
# Safe to run from anywhere — paths are resolved relative to this script.
# Re-runs on every build; output is deterministic for a clean tree at a given commit.

set -euo pipefail

MAJOR=3

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
out="$here/version.h"

# Resolve commit count + dirty state. Tolerate non-git environments (e.g. a
# tarball release) by falling back to "0-nogit".
if git -C "$here" rev-parse --git-dir >/dev/null 2>&1; then
  commits="$(git -C "$here" rev-list --count HEAD 2>/dev/null || echo 0)"
  if [ -n "$(git -C "$here" status --porcelain 2>/dev/null || true)" ]; then
    suffix="-dev"
  else
    suffix=""
  fi
  short_sha="$(git -C "$here" rev-parse --short HEAD 2>/dev/null || echo unknown)"
else
  commits="0"
  suffix="-nogit"
  short_sha="unknown"
fi

version="${MAJOR}.${commits}${suffix}"

# Only rewrite the file if the version changed — avoids touching mtime on every
# build, which would force arduino-cli to recompile the whole sketch needlessly.
new_contents=$(cat <<EOF
// Auto-generated by generate_version.sh — do not edit by hand.
// Gitignored. Regenerated before every build by the flash skill and CI.
#pragma once
#define FIRMWARE_VERSION "${version}"
#define FIRMWARE_COMMIT_SHORT "${short_sha}"
EOF
)

if [ -f "$out" ] && [ "$(cat "$out")" = "$new_contents" ]; then
  echo "version.h already up to date: ${version}"
else
  echo "$new_contents" > "$out"
  echo "Wrote version.h: ${version}"
fi
